vars:
  # DevGPT dataset: https://github.com/NAIST-SE/DevGPT
  - DevGPT:
      version: 'v9'
      zenodo_id: 10086809
  # where to clone Git repositories
  - repositories_dir: /mnt/data/MSR_Challenge_2024/repositories/
stages:
  download_DevGPT:
    desc: 'Download DevGPT dataset ${DevGPT.version} from Zenodo'
    cmd:
      - dvc get-url --force https://zenodo.org/records/${DevGPT.zenodo_id}/files/DevGPT.zip?download=1
      - mkdir -p data/external
      - unzip DevGPT.zip -d data/external/DevGPT
      - rm DevGPT.zip
    outs:
      - data/external/DevGPT/

  clone_repos:
    desc: 'Clone all repositories included in DevGPT dataset'
    cmd: >-
      python scripts/data/download_repositories.py
      data/external/DevGPT/ ${repositories_dir}
      data/repositories_download_status.json
    deps:
      - scripts/data/download_repositories.py
      - data/external/DevGPT/
    outs:
      - data/repositories_download_status.json:
          cache: false
