---
    config:
        sankey:
            height: 900
            width: 500
---

sankey-beta
PR,"P [0.0, 0.25]",124
PR,"P [0.0, 0.25]",54
PR,"P (0.25, 0.5]",17
PR,"P (0.5, 0.75]",10
PR,"P (0.75, 1.0]",30
commits,"c [0.0, 0.25]",55
commits,"c (0.25, 0.5]",52
commits,"c (0.5, 0.75]",129
commits,"c (0.75, 1.0]",193
"P [0.0, 0.25]",NOT MERGED,54
"P [0.0, 0.25]",MERGED,124
"P (0.25, 0.5]",MERGED,17
"P (0.5, 0.75]",MERGED,10
"P (0.75, 1.0]",MERGED,30
"c [0.0, 0.25]",MERGED,55
"c (0.25, 0.5]",MERGED,52
"c (0.5, 0.75]",MERGED,129
"c (0.75, 1.0]",MERGED,193
